sudo: false
language: rust
matrix:
  include:
    - os: windows
      rust: stable
    - os: osx
      rust: stable
    - os: linux
      rust: stable

cache: cargo

script:
  - cargo test -v --no-fail-fast
  - cargo test -v --no-fail-fast --features preserve_order
  - cargo test -v --no-fail-fast --features inline_comment
  - cargo doc --no-deps
